#!/bin/bash
# SPDX-License-Identifier: GPL-3.0+
# Copyright (C) 2024 John Meneghini <jmeneghi@redhat.com>
#
# Test nvme-fc marginal path handling with fcloop

. tests/nvme/rc

DESCRIPTION="test nvme-fc marginal path handling"

requires() {
	_nvme_requires
	_have_loop
	_have_fio
	_require_nvme_trtype fc
}

set_conditions() {
	_set_nvme_trtype "$@"
}

_wait_for_ctrl_state() {
	local def_state_timeout=5
	local nvmedev="$1"
	local state="$2"
	local timeout="${3:-$def_state_timeout}"
	local state_file
	local start_time
	local end_time

	state_file="/sys/class/nvme/${nvmedev}/state"

	start_time=$(date +%s)
	until grep -q "${state}" "${state_file}"; do
		sleep 1
		end_time=$(date +%s)
		if (( end_time - start_time > timeout )); then
			echo "expected state \"${state}\" not " \
				"reached within ${timeout} seconds"
			return 1
		fi
	done

	return 0
}

#we need to filter these
_subsys_get_rports() {
	local SUBSYS=$1 # /sys/devices/virtual/nvme-subsystem/nvme-subsys3

	printf "%s\n" "$SUBSYS"/nvme* | grep -Eo ".*nvme[0-9]+$"
	# /sys/devices/virtual/nvme-subsystem/nvme-subsys3/nvme9
}

_subsys_host_get_rports() {
	local SUBSYS=$1 # /sys/devices/virtual/nvme-subsystem/nvme-subsys3
	local HOST_TRADDR=$2 # nn-0x200000109b5f2957:pn-0x100000109b5f2957

	for subsys_path in $(_subsys_get_rports "$SUBSYS"); do
		grep -l host_traddr="$HOST_TRADDR" "$subsys_path"/address && echo "$subsys_path" || true
	done
	# /sys/devices/virtual/nvme-subsystem/nvme-subsys3/nvme9
}











_subsys_rport_addr() {
	local RPORT=$1 # /sys/devices/virtual/nvme-subsystem/nvme-subsys3/nvme9

	cat "$RPORT"/address
	# traddr=nn-0x2047d039ea98949e:pn-0x2048d039ea98949e,host_traddr=nn-0x200000109b9b7e4e:pn-0x100000109b9b7e4e
}

_subsys_get_port() {
	local RPORT=$1 # /sys/devices/virtual/nvme-subsystem/nvme-subsys3/nvme9
	local port
	local address

	address=$(_subsys_rport_addr "$RPORT")
	port=$(echo "$address" | sed -n 's/.*pn-\(.*\),.*/\1/p')
	echo $(( $port - $(_remote_wwpn 0) ))
	# a number representing the port number, e.g. 0, 1, 2, 3
}

_rport_set_marginal() {
	local RPORT=$1 # /sys/devices/virtual/nvme-subsystem/nvme-subsys3/nvme9

	_setup_nvmet_port_marginal "$(_subsys_get_port "$RPORT")" "marginal"
}

_rport_set_online() {
	local RPORT=$1 # /sys/devices/virtual/nvme-subsystem/nvme-subsys3/nvme9

	_setup_nvmet_port_marginal "$(_subsys_get_port "$RPORT")" "live"
}

_rport_is_online() {
	local RPORT=$1 # /sys/devices/virtual/nvme-subsystem/nvme-subsys3/nvme9

	[[ "$(cat "$RPORT"/state)" == "live" ]]
	# Returns Success or Fail
}

_rport_is_marginal() {
	local RPORT=$1 # /sys/devices/virtual/nvme-subsystem/nvme-subsys3/nvme9

	[[ "$(cat "$RPORT"/state)" == "marginal" ]]
	# Returns Success or Fail
}

_rport_in_use() {
	local SUBSYS_PATH=$1 # /sys/devices/virtual/nvme-subsystem/nvme-subsys3/nvme9

	# there should only be one "nvme3c9n1" afaik
	[[ "$(cat "$SUBSYS_PATH"/nvme*/stat | awk '{print $9}')" != "0" ]]
	# Returns exit code 0 if in use, 1 if not in use
}

_rport_optimized() {
	local SUBSYS_PATH=$1 # /sys/devices/virtual/nvme-subsystem/nvme-subsys3/nvme9

	# there should only be one "nvme3c9n1" afaik
	[[ "$(cat "$SUBSYS_PATH"/nvme*/ana_state)" == "optimized" ]]
	# Returns exit code 0 if optimized, 1 if not optimized
}

# check if link is marginal or not
_rport_check_online() {
	local RPORT=$1 # /sys/devices/virtual/nvme-subsystem/nvme-subsys3/nvme9
	local STATE=$2 # "Online"

	if [[ "$STATE" == "Online" ]]; then
		if ! _rport_is_online "$RPORT"; then
			echo  FC port \("$RPORT"\) is not online, expteced online.
			return 1
		fi
	else
		if ! _rport_is_marginal "$RPORT"; then
			echo FC port \("$RPORT"\) is not marginal, expteced marginal.
			return 1
		fi
	fi
	# Returns Success or Fail
}

# check if link is in use
_rport_check_use() {
	local RPORT=$1 # /sys/devices/virtual/nvme-subsystem/nvme-subsys3/nvme9
	local STATE=$2 # "Online"

	if [[ "$STATE" == "Online" ]]; then
		if ! _rport_in_use "$RPORT" ; then
			echo FC port on \("$RPORT"\) is not being used, expected use.
			return 1
		fi
	else
		if _rport_in_use "$RPORT" ; then
			echo FC port on \("$RPORT"\) is being used, expected no use.
			return 1
		fi
	fi
	# Returns Success or Fail
}

# check if link is in use if optimized
_rport_check_use_opt() {
	local RPORT=$1 # /sys/devices/virtual/nvme-subsystem/nvme-subsys3/nvme9

	# Only optimized paths will be in use
	if _rport_optimized "$RPORT"; then
		_rport_check_use "$RPORT" Online
	else
		_rport_check_use "$RPORT" Marginal
	fi
	# Returns Success or Fail
}

# check if all link is in state and use state if optimized
_rport_check_opt() {
	local RPORT=$1 # /sys/devices/virtual/nvme-subsystem/nvme-subsys3/nvme9
	local STATE=$2 # "Online"

	_rport_check_online "$RPORT" "$STATE"
	# Only optimized paths will be in use
	if _rport_optimized "$RPORT"; then
		_rport_check_use "$RPORT" "$STATE"
	else
		_rport_check_use "$RPORT" Marginal
	fi
	# Returns Success or Fail
}

# check if all link is in state and use state
_rport_check() {
	local RPORT=$1 # /sys/devices/virtual/nvme-subsystem/nvme-subsys3/nvme9
	local STATE=$2 # "Online"

	_rport_check_online "$RPORT" "$STATE"
	_rport_check_use "$RPORT" "$STATE"
	# Returns Success or Fail
}

matching_vals() {
	local value=$1
	local -a KEYS=( $2 )
	local -a VALS=( $3 )

	for i in "${!KEYS[@]}"; do
		[[ "${VALS[i]}" == "$value" ]] && echo "${KEYS[i]}" || true
	done
}

# check if all links are of expected state on host
_rport_check_host() {
	local STATE=$1 # "Online"
	local HOST=$2 # host1
	local -a RPORTS_PATHS=( $3 ) # /sys/devices/virtual/nvme-subsystem/nvme-subsys3/nvme9
	local -a RPORTS_HOSTS=( $4 ) # host1 host2

	for subsys_path in $(matching_vals "$HOST" "${RPORTS_HOSTS[*]}" "${RPORTS_PATHS[*]}"); do
		_rport_check_opt "$subsys_path" "$STATE"
	done
	# Returns Success or Fail
}


# Check if one of the marginal paths is in use
_rport_check_one_use_online() {
	local RPORTS_PATHS=("$@") #  /sys/devices/virtual/nvme-subsystem/nvme-subsys3/nvme9

	# Check if one of the online paths is in use
	for subsys_path in "${RPORTS_PATHS[@]}"; do
		# If path is Marginal, continue to the next path
		_rport_check_online "$subsys_path" Online || continue
		# One of the online paths should be in use
		# "!" inverts the return code, so returns false if path is in use,
		# running the return statement
		! _rport_check_use "$subsys_path" || return 0
	done

	echo No FC ports are being used, expected atleast one in use when all are online in numa mode.
	# None of the online paths were in use
	return 1

	# Returns Success or Fail
}

test_set_all_online() {
	local IOPOLICY=$1 # "numa" "queue-depth" "round-robin"
	local -a RPORTS_PATHS=( $2 ) # /sys/devices/virtual/nvme-subsystem/nvme-subsys3/nvme9

	for subsys_path in "${RPORTS_PATHS[@]}"; do
		_rport_set_online "$subsys_path" || return 1
		_rport_check_online "$subsys_path" Online || return 1
	done

	if [ "$IOPOLICY" == "numa" ]; then
		_rport_check_one_use_online "${RPORTS_PATHS[@]}" || return 1
	else
		for subsys_path in "${RPORTS_PATHS[@]}"; do
			# Only optimized paths will be in use
			_rport_check_opt "$subsys_path" Online || return 1
		done
	fi
}

test_set_one_host_marginal() {
	local HOST=$1 # host1
	local -a RPORTS_PATHS=( $2 ) # /sys/devices/virtual/nvme-subsystem/nvme-subsys3/nvme9
	local -a RPORTS_HOSTS=( $3 ) # host1 host2

	for subsys_path in $(matching_vals "$HOST" "${RPORTS_HOSTS[*]}" "${RPORTS_PATHS[*]}"); do
		_rport_set_marginal "$subsys_path" || return 1
	done

	for host in "${RPORTS_HOSTS[@]}"; do
		if [[ "$host" == "$HOST" ]]; then
			_rport_check_host Marginal "$host" "${RPORTS_PATHS[*]}" "${RPORTS_HOSTS[*]}" || return 1
		else
			_rport_check_host Online "$host" "${RPORTS_PATHS[*]}" "${RPORTS_HOSTS[*]}" || return 1
		fi
	done
}


test_set_all_host_marginal() {
	local -a RPORTS_PATHS=( $1 ) # /sys/devices/virtual/nvme-subsystem/nvme-subsys3/nvme9

	for subsys_path in "${RPORTS_PATHS[@]}"; do
		_rport_set_marginal "$subsys_path" || return 1
		_rport_check_opt "$subsys_path" Marginal || return 1
	done
}

test_set_one_non_optimized_online() {
	local -a RPORTS_PATHS=( $1 ) # /sys/devices/virtual/nvme-subsystem/nvme-subsys3/nvme9

	# Set one non-optimized online
	# First set one non-optimized online to online then check optimized paths
	local next_marginal=0
	for subsys_path in "${RPORTS_PATHS[@]}"; do
		if ! subsys_path_optimized "$subsys_path"; then
			if [ $next_marginal == 1 ]; then
				fc_check "$subsys_path" Marginal || return 1
				break
			fi
			fc_rport_set_online "$(subsys_path_get_fc_rport "$subsys_path")"
			fc_check "$subsys_path" Online || return 1
			next_marginal=1
		fi
	done
	# Check optimized paths
	for subsys_path in "${RPORTS_PATHS[@]}"; do
		if subsys_path_optimized "$subsys_path"; then
			# Optimized paths will not be in use
			fc_check_opt "$subsys_path" Marginal || return 1
		fi
	done
}

run_test() {
	local IOPOLICY=$1 # "numa" "queue-depth" "round-robin"
	local -a RPORTS_PATHS=( $2 ) # /sys/devices/virtual/nvme-subsystem/nvme-subsys3/nvme9
	local -a RPORTS_HOSTS=( $3 ) # host1 host2
	local err=0

	echo Changing FC links to online
	# Initial check to see if FC is operational and set ports to online
	test_set_all_online "$IOPOLICY" "${RPORTS_PATHS[*]}" && echo "Set all online: pass" || echo "Set all online: fail"

	test_set_one_host_marginal "${RPORTS_HOSTS[0]}" "${RPORTS_PATHS[*]}" "${RPORTS_HOSTS[*]}" && echo "One host marginal: pass" || echo "One host marginal: fail"
	test_set_all_host_marginal "${RPORTS_PATHS[*]}" && echo "All marginal: pass" || echo "All marginal: fail"

	test_set_one_non_optimized_online "${RPORTS_PATHS[*]}" && echo "One remote non-optimized online: pass" || echo "One remote non-optimized online: fail"
	#test_set_two_non_optimized_online "$SUBSYS" "$IOPOLICY" "${FC_HOSTS[@]}" && echo "Two remote non-optimized online: pass" || echo "Two remote non-optimized online: fail"

	#test_set_two_non_one_optimized_online "$SUBSYS" "${FC_HOSTS[@]}" && echo "Two remote non-optimized, One remote optimized: pass" || echo "Two remote non-optimized, One remote optimized: fail"

	#test_set_all_online "$SUBSYS" "$IOPOLICY" "${FC_HOSTS[@]}" && echo "All online: pass" || echo "All online: fail"


	# Set one optimized online
	#send_fpin_link_integrity_event "$(get_fc_host_port_id "${FC_HOSTS[0]}")" "$FPINTYPE" || err=1
	#if [[ $err != 0 ]]; then
	#	echo "Failed to send FPIN event on ${FC_HOSTS[0]}"
	#	err=0
	#fi
	#send_fpin_link_integrity_event "$(get_fc_host_port_id "${FC_HOSTS[1]}")" "$FPINTYPE" || err=1
	#if [[ $err != 0 ]]; then
	#	echo "Failed to send FPIN event on ${FC_HOSTS[1]}"
	#	err=0
	#fi
	#test_set_one_optimized_online "$SUBSYS" "${FC_HOSTS[@]}" && echo "One remote optimized online: pass" || echo "One remote optimized online: fail"
	#test_set_two_optimized_online "$SUBSYS" "$IOPOLICY" "${FC_HOSTS[@]}" && echo "Two remote optimized online: pass" || echo "Two remote optimized online: fail"
	#test_set_all_online "$SUBSYS" "$IOPOLICY" "${FC_HOSTS[@]}" && echo "All online: pass" || echo "All online: fail"
}

do_test() {
	local nvmedev="$1"
	local ns="$2"
	local port=0
	local fio_pid

	# Verify initial controller state is online
	#_wait_for_ctrl_state "$nvmedev" "live" 0 || { echo "FAIL: Controller unexpectedly started as not online."; return 1; }

	# Start background I/O
	echo "Starting background I/O"
	_run_fio_verify_io --filename="/dev/${ns}" \
			   --group_reporting --ramp_time=5 \
			   --time_based --runtime=1m &> "$FULL" &
	fio_pid=$!
	sleep 5
	local RPORTS_PATHS=/sys/class/nvme/${nvmedev}
	local RPORTS_HOSTS=host1
	run_test round-robin "$RPORTS_PATHS" "$RPORTS_HOSTS"
	# Stop background I/O
	echo "Stopping background I/O"
	{ kill "$fio_pid"; wait; } &> /dev/null
}

test() {
	local nvmedev
	local ns

	echo "Running ${TEST_NAME}"

	_setup_nvmet

	_nvmet_target_setup --ports 1

	_nvme_connect_subsys
	nvmedev=$(_find_nvme_dev "${def_subsysnqn}")

	do_test "$nvmedev" "$ns"

	_nvme_disconnect_subsys
	_nvmet_target_cleanup

	echo "Test complete"
}
